### ISSUE TITLE
compile error master

### ISSUE THREAD

**Issue by mkrzewic** [vmc-project/geant4_vmc#1]
Hi,
i'm getting this when trying to compile master:

[  2%] Building CXX object g4root/test/OpNovice/CMakeFiles/g4root_OpNovice.dir/src/OpNovicePhysicsList.cc.o
/home/mkrzewic/alfa/sw/SOURCES/GEANT4_VMC/master_O2/0/g4root/test/OpNovice/src/OpNovicePhysicsList.cc: In member function ‘void OpNovicePhysicsList::ConstructDecay()’:
/home/mkrzewic/alfa/sw/SOURCES/GEANT4_VMC/master_O2/0/g4root/test/OpNovice/src/OpNovicePhysicsList.cc:127:45: error: ‘GetParticleIterator’ was not declared in this scope
   auto particleIterator=GetParticleIterator();
                                             ^
/home/mkrzewic/alfa/sw/SOURCES/GEANT4_VMC/master_O2/0/g4root/test/OpNovice/src/OpNovicePhysicsList.cc: In member function ‘void OpNovicePhysicsList::ConstructEM()’:
/home/mkrzewic/alfa/sw/SOURCES/GEANT4_VMC/master_O2/0/g4root/test/OpNovice/src/OpNovicePhysicsList.cc:165:45: error: ‘GetParticleIterator’ was not declared in this scope
   auto particleIterator=GetParticleIterator();
                                             ^
/home/mkrzewic/alfa/sw/SOURCES/GEANT4_VMC/master_O2/0/g4root/test/OpNovice/src/OpNovicePhysicsList.cc: In member function ‘void OpNovicePhysicsList::ConstructOp()’:
/home/mkrzewic/alfa/sw/SOURCES/GEANT4_VMC/master_O2/0/g4root/test/OpNovice/src/OpNovicePhysicsList.cc:240:6: error: ‘IsMasterThread’ is not a member of ‘G4Threading’
   if(G4Threading::IsMasterThread())
      ^~~~~~~~~~~
/home/mkrzewic/alfa/sw/SOURCES/GEANT4_VMC/master_O2/0/g4root/test/OpNovice/src/OpNovicePhysicsList.cc:247:45: error: ‘GetParticleIterator’ was not declared in this scope
   auto particleIterator=GetParticleIterator();
                                             ^
g4root/test/OpNovice/CMakeFiles/g4root_OpNovice.dir/build.make:134: recipe for target 'g4root/test/OpNovice/CMakeFiles/g4root_OpNovice.dir/src/OpNovicePhysicsList.cc.o' failed
make[2]: *** [g4root/test/OpNovice/CMakeFiles/g4root_OpNovice.dir/src/OpNovicePhysicsList.cc.o] Error 1
CMakeFiles/Makefile2:160: recipe for target 'g4root/test/OpNovice/CMakeFiles/g4root_OpNovice.dir/all' failed
make[1]: *** [g4root/test/OpNovice/CMakeFiles/g4root_OpNovice.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ihrivnac** [comment]
Hi,
It looks like you use incompatible versions of Geant4 VMC and Geant4. Could you let me know which versions you have?
Ivana

**Comment by mkrzewic** [comment]
Hi, indeed, I was using an older version. closing.
