### ISSUE TITLE
Issues setting up geant4_vmc for Monte Carlo Simulation with ROOT

### ISSUE THREAD

**Issue by stephen-mul** [vmc-project/geant4_vmc#15]
_ROOT Version: 6.18.04
_Platform: Windows 10
_Compiler: Visual Studio 2019

I’m trying to setup geant4_vmc following the installation instructions provided. There seems to be some issue finding ROOT when I run Cmake as follows:

`cmake -DCMAKE_INSTALL_PREFIX="%HOMEPATH%\geant4_vmc\geant4_vmc_install" “%HOMEPATH%\geant4_vmc\geant4_vmc.4.0.p1” -DROOT_DIR=“C:\Users\Stephen\ROOT\root_v6.18.04” -DGeant4_DIR=“C:\Users\Stephen\Geant4\geant4_10_06_p01”`

and I get the error

![errorgeant4_vmc-findDirectory2](https://user-images.githubusercontent.com/63642042/80817410-a9b72800-8bd1-11ea-96cb-2a93533e7cbe.PNG)

I've been told that the error is coming from [this line](https://github.com/vmc-project/geant4_vmc/blob/v4-0-p1/cmake/FindROOT.cmake#L80), but I don't know how to rectify the problem.

If anyone had a fix for this issue I would really appreciate it. I'm quite new to both Geant4 and ROOT so apologies if this is trivial or poorly worded.

**Comment by ihrivnac** [comment]
Hello,
Please note that though both ROOT and Geant4 support Windows, the VMC project supported platforms are only Linux and Mac OS.
On the other hand, from your report it is clear that you are trying incompatible versions. You need Geant4 VMC 5.1.p1 (the v5-1-p1 tag in GitHub) when using with Geant4 10.6.x.
In this version, FindROOT.cmake is never more present, so it may help.

**Comment by stephen-mul** [comment]
Thanks very much for the explanation
