### ISSUE TITLE
Mass value in TVirtualMC->DefineIon

### ISSUE THREAD

**Issue by SchetininVitaliy** [vmc-project/geant4_vmc#16]
Hi,

I am developing FairRoot based package and need to transport light exotical ion with defined mass using it. I am using FairRunSim::AddNewIon(2 /*Z*/, 10 /*A*/, 2 /*Q*/, 0. /*Exc*/, 10/*Gev*/), for example to create new ion. But  I see in the log that an ion is created with a mass different from the one I set. 

I have investigate this problem and see that defined mass skipped in

```
Bool_t TG4PhysicsManager::DefineIon(const char* name, Int_t Z, Int_t A, Int_t Q,
  Double_t excEnergy, Double_t /*mass*/)
```

Is it possible to correct the creation of an ion by replacing the G4IonTable::GetIon, 
on G4IonTable::Insert()?

I can create Pull  Request on this, but maybe you know in advance that this is a bad idea and stop me)

**Comment by ihrivnac** [comment]
Hi Vitaliy,

The `G4IonTable::Insert()` has a different arguments  list than `G4IonTable::GetIon()`, so a simple replacement of the call in TG4PhysicsManager  is not possible (or have you tried your suggestion?). 

 I will ask Geant4  experts how can we set the user mass value to an ion. 

Best regards,

**Comment by SchetininVitaliy** [comment]
Hi Ivana,

I have not tried it yet.
But I will try to use way presented in http://www.apc.univ-paris7.fr/~franco/g4doxy/html/G4IonTable_8cc-source.html#l00185

Best Regards

**Comment by ihrivnac** [comment]
Closing issue as there is no further feedback from @SchetininVitaliy . Please, re-open it again if needed.
