### ISSUE TITLE
Process names in specialControls use Geant3 process names

### ISSUE THREAD

**Issue by janerhein** [vmc-project/geant4_vmc#32]
Hello,

I was recently using geant4_vmc to turn off some processes in a few materials for my simulation application.
The process is described in:
 https://vmc-project.github.io/user-guide/geant4_vmc/physics-lists/
Looking through the source code, it became apparent that the process names one needs to specify are the ones from Geant3. A "list" can be found in:
 https://github.com/vmc-project/geant4_vmc/blob/b1442f7bbbf44617fbeca7fb2491eee76df121e0/source/global/src/TG4G3ControlVector.cxx#L10
I was wondering whether it might be possible and beneficial to provide support for Geant4 process names too. Not only would this increase ease of use, but it would also allow for a more detailed selection of processes. 
Geant4 splits some of the aforementioned processes up into several subprocesses. Overall this leads to more choice in possible selections.

**Comment by ihrivnac** [comment]
Hello,

The implementation of switching selected processes per material for Geant4 is quite tricky and at the end it does not bring any benefit in performance. On the other hand, I agree, that it can be useful for various studies.

To extend the current implementation to allow switching any Geant4 process would require to extend the information that is now hold in TG4Limits object, and then adapt the TG4SpecialControlsV2 class for this or create its variant, V3.
I will add it on the updates plans.

Best regards,
