### ISSUE TITLE
Unexpected pdg code when creating ions

### ISSUE THREAD

**Issue by fuhlig1** [vmc-project/geant4_vmc#4]
Hi,

when using FairRoot with geant4_vmc to create a new ion via the following function

        TVirtualMC->DefineIon(ion->GetName(), ion->GetZ(), ion->GetA(), ion->GetQ(),
                                               ion->GetExcEnergy(),ion->GetMass());
 
I get in some cases an unexpected pdg code (see example below). Trying to create several La isotopes with a different number of neutrons (z always 57) for three isotopes the pdg code indicates that the isotope is in an excited state. All other isotopes have the expected pdg code.  

> [INFO   ] Going to register ion Ion_120_57_0 with pdg code 1000571200 and (Z,A,Q,ExcEnergy,Mass) 57, 120, 57, 0.000, 112.6 (log from FairRoot)
> Adding ion with Z, A, Q, excEnergy [keV]: 57 120 57 0 (log from TG4ParticlesManager.cxx )
> Adding particle to TDatabasePDG 
>    name:   La120[0.000]
>    g4name: Ion_120_57_0
>    PDG:    1000571201
>    pdgQ:   57
>    type:   Ion

For me it is not clear if the problem is in geant4_vmc or Geant4 itself.

**Comment by ihrivnac** [comment]
Hi @fuhlig1 ,
I will check, it looks like a problem in  geant4_vmc .
Could, you, please, give me your three ion definitions and their PDG obtained, and also your versions of geant4_vmc and Geant4?

**Comment by fuhlig1** [comment]
Hi @ihrivnac,

I am trying to create ions with Z=57 and A running from 117 to 155. For the following three ions it results in an unexpected dpg code.

Ion_121_57_0 with (Z,A,Q,ExcEnergy,Mass) 57, 121, 57, 0.000, 113.5
Ion_124_57_0 with (Z,A,Q,ExcEnergy,Mass) 57, 124, 57, 0.000, 116.3
Ion_126_57_0 with (Z,A,Q,ExcEnergy,Mass) 57, 126, 57, 0.000, 118.2

The used versions are

geant4_vmc: 3.3.0
Geant4: 10.2.1

**Comment by ihrivnac** [comment]
The PDG code 1000571201 etc. is generated by Geant4. I checked that the problem persists in 10.2.p03, it was fixed in the next Geant4 version 10.3. I checked with 10.3.p03, and get 1000571200 as expected.
Is it possible for you to switch to this later Geant4 version?

**Comment by fuhlig1** [comment]
> The PDG code 1000571201 etc. is generated by Geant4. I checked that the problem persists in 10.2.p03, it was fixed in the next Geant4 version 10.3. I checked with 10.3.p03, and get 1000571200 as expected.

Thanks for your investigation. This is what I have expected. I will try to do a check on my own If I get the correct peg code when using the latest Geant4 with FairRoot.

> Is it possible for you to switch to this later Geant4 version?

For the current CbmRoot release I think there is no possibility to switch to the latest Geant4 version. Do you see any chance to have a fix inside of geant4vmc and produce a patch release of geant4vmc 3.3?

**Comment by ihrivnac** [comment]
I can prepare a patch so that VMC will return the PDG code corrected just for the ions with Z=57. 
But this will not fix the problem with these ions in Geant4. I asked a view of Vladimir Ivantchenko, who replied:
"With Geant4 10.2 we have a problem: ions with a bit non-precise value of excitation energy were created and after tracked by Geant4. I afraid, I have no good proposal how making work  around. The best for me, would be ignoring such ions, which carrying out small kinetic energy. "

So what I can propose for Geant4 VMC is following:
When an ion is defined with Exc energy = 0 and gets the PDG code ending with !=0, the Geant4 VMC will issue a warning that this ion is problematic and adjusts the PDG code to end with 0.

**Comment by fuhlig1** [comment]
We are investigating in the moment the usage of Geant4 10.4 for our release. If this turns out to be possible this would be a much better solution. So please don’t waste your time to implement a hack.

If we are able to use Geant4 10.4 I will close the issue.

**Comment by ihrivnac** [comment]
I agree, that this would be the best solution.

**Comment by fuhlig1** [comment]
I close the issue since we meanwhile are using a fixed Geant4 version.
