### ISSUE TITLE
Tests can not be run without X11 display

### ISSUE THREAD

**Issue by olifre** [vmc-project/geant4_vmc#42]
This may well be an issue of my setup, but since updating to `geant4_vmc-6.2` (and correspondingly, Geant 4.11.1.0) I observe the following when running tests, here for example with test E06 run manually:
```
$ unset DISPLAY
$ ./g4vmc_testE06
...
### Processes mapped to VMC codes ok
TG4ComposedPhysicsList::ConstructProcess done
Available UI session types: [ Qt, Xm, tcsh, csh ]
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted
```
I did not see an obviously related change in the code to this, so it might be something in my environment which is different. I observe the same with the ROOT macro based tests. 

Do you have an idea what could be wrong? Any help / pointers to find the cause are appreciated :-).

**Comment by ihrivnac** [comment]
When you run the test executable without specifying any options on the command line, the test runs with the default arguments and executes the `g4vis.in` macro, see the beginning of the output:
```
 Running testE06 with options:
   --g4-geometry:        geomRootToGeant4
   --g4-physics-list:    emStandard+optical
   --g4-special-physics: stepLimiter
   --g4-macro:           g4config.in
   --g4-macro2:          g4config2.in
   --g4-vis-macro:       g4vis.in
```
To disable it, you should call the test with the option:
```
g4vmc_testE06 --g4-vis-macro "" 
```

**Comment by olifre** [comment]
Dear Ivana,

thanks, that's very helpful! 

Indeed, I realized I must always have run the tests with X11 in the past. Since I need to run the full test suite in Gentoo packaging, but can't rely on X11 being present there "automatically", I'll use a small Xvfb server to ensure the full test suite can always be run, even on "headless" systems. I can confirm this makes all tests pass even if there is no "real" X11 server present :-). 

Since this is not really an issue of `geant4_vmc` (unless there would be a way to run the full test suite without X11, which would of course be nicer) I'll close this one. Thanks again!
