### ISSUE TITLE
core dumped during writing root file

### ISSUE THREAD

**Issue by TanmayeeSamal** [vmc-project/geant4_vmc#63]
am using Geant4 version 11.2.1
Before using the output.root file, I got the photon position, detector position etc
After adding the output.root, it will give error massage after the projection of beam.
"Detector Position: (-115,25,490)
Segmentation fault (core dumped)"
I have replaced g4root.hh to G4AnalysisManager.hh in run.hh. There is no compiling error. The error occurs during writing the output file.
please suggest me how to rectify the error.

**Comment by ihrivnac** [comment]
Hello @TanmayeeSamal ,

Could you, please, give more details about your application ? Is your code based on the [VMC](https://vmc-project.github.io/) framework (via calls to the `TVirtualMC` class) or do you define your Geant4 application with Geant4 user classes ?

**Comment by ihrivnac** [comment]
Closing because no news from the user. Please, reopen, if the problem persists.
